spring.application.name=fast-campus-course-rag

app.cli.enabled=false

app.etl.pipeline.init=true

app.vectorstore.in-memory.enabled=false

app.rag.documents-location-pattern=classpath:fastcampus-springai.pdf


logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-nano
spring.ai.openai.chat.base-url=https://api.openai.com/v1
spring.ai.openai.chat.completions-path=/chat/completions

spring.ai.model.chat=ollama
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.init.pull-model-strategy=when_missing

spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.options.model=bge-m3

spring.ai.vectorstore.opensearch.uris=http://localhost:9200
spring.ai.vectorstore.opensearch.initialize-schema=true
spring.ai.vectorstore.opensearch.index-name=spring-ai-document-index